name: Update Data

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with: 
          token: ${{ secrets.TOKEN }}

      - name: Run JavaScript Function
        run: |
          node create-file.js
      
      - name: Commit and Push New File
        run: |
          git config user.name "ddsuhaimi"
          git config user.email "dedisuhaimiacc@gmail.com"
          git add .
          git commit --allow-empty -m "generated"
          git push
